framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    # milliseconds delay
                    delay: 4000
                    # causes the delay to be higher before each retry
                    # e.g. 1-second delay, 2 seconds, 4 seconds
                    multiplier: 10
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
        # Route your messages to the transports
#            'App\AAA\Application\Command\ChatMessage\ABC\ABS': async

when@test:
    framework:
        messenger:
            transports:
                async: 'sync://'
