users:
  resource:
    path: ../src/Users/Controller/
    namespace: App\Users\Controller\
  type: attribute

security:
  resource:
    path: ../src/Security/Controller/
    namespace: App\Security\Controller\
  type: attribute

products:
  resource:
    path: ../src/Products/Controller/
    namespace: App\Products\Controller\
  type: attribute

orders:
  resource:
    path: ../src/Orders/Controller/
    namespace: App\Orders\Controller\
  type: attribute