users:
  resource:
    path: ../src/Users/Infrastructure/Controller/
    namespace: App\Users\Infrastructure\Controller\
  type: attribute

security:
  resource:
    path: ../src/Security/Infrastructure/Controller/
    namespace: App\Security\Infrastructure\Controller\
  type: attribute

products:
  resource:
    path: ../src/Products/Infrastructure/Controller/
    namespace: App\Products\Infrastructure\Controller\
  type: attribute

orders:
  resource:
    path: ../src/Orders/Infrastructure/Controller/
    namespace: App\Orders\Infrastructure\Controller\
  type: attribute